ALTER TABLE rollingpaper ADD classification VARCHAR(255) NOT NULL
DEFAULT 'MEMBER';

ALTER TABLE rollingpaper MODIFY COLUMN member_id bigint;

ALTER TABLE message ADD anonymous BOOL NOT NULL
DEFAULT FALSE;

ALTER TABLE message ADD secret BOOL NOT NULL
DEFAULT FALSE;

ALTER TABLE team ADD secret BOOL NOT NULL
DEFAULT FALSE;
