spring:
  datasource:
    source:
      hikari:
        jdbc-url: ${SOURCE_MYSQL_URL}
        password: ${SOURCE_MYSQL_PASSWORD}
        username: ${SOURCE_MYSQL_USERNAME}
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: ${SOURCE_MAX_CONNECTION_POOL_SIZE}
    replica:
      hikari:
        jdbc-url: ${REPLICA_MYSQL_URL}
        password: ${REPLICA_MYSQL_PASSWORD}
        username: ${REPLICA_MYSQL_USERNAME}
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: ${REPLICA_MAX_CONNECTION_POOL_SIZE}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}


  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    generate-ddl: false
  flyway:
    enabled: true
    baseline-on-migrate: true

security:
  jwt:
    token:
      expire-length: ${JWT_EXPIRE_LENGTH}
      secret-key: ${JWT_SECRET_KEY}
  aes256:
    key: ${AES256_KEY}
  invite-expire-length: 86400000

kakao:
  admin-key: ${KAKAO_ADMIN_KEY}
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}

logging:
  config: classpath:log4j2-deploy.yml
