spring:
  h2:
    console:
      enabled: true
  profiles:
    active: local
  datasource:
    #    url: jdbc:h2:tcp://localhost/~/naepyeon
    url: jdbc:mysql://localhost:3306/naepyeon?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true
#    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: root
    password: root
#    driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션
    open-in-view: false
    generate-ddl: false
  flyway:
    enabled: true
    baseline-on-migrate: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

security:
  jwt:
    token:
      secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
      expire-length: 3600000