spring:
  datasource:
    source:
      hikari:
        jdbc-url: ${SOURCE_MYSQL_URL}
        password: ${SOURCE_MYSQL_PASSWORD}
        username: ${SOURCE_MYSQL_USERNAME}
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: ${MAX_CONNECTION_POOL_SIZE}
    replica:
      hikari:
        jdbc-url: ${REPLICA_MYSQL_URL}
        password: ${REPLICA_MYSQL_PASSWORD}
        username: ${REPLICA_MYSQL_USERNAME}
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: ${MAX_CONNECTION_POOL_SIZE}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true

security:
  jwt:
    token:
      secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
      expire-length: 3600000
  aes256:
    key: ${AES256_KEY}
  invite-expire-length: 86400000

kakao:
  admin-key: ${KAKAO_ADMIN_KEY}
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}

server:
  tomcat:
    accept-count: ${TOMCAT_ACCEPT_COUNT}
    threads:
      max: ${MAX_THREAD_POOL_SIZE}
    max-connections: ${TOMCAT_MAX_CONNENCTIONS}


logging:
  config: classpath:log4j2-develop.yml
