spring:
  datasource:
    source:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3306/naepyeon?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true
        username: user
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
    replica:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3307/naepyeon?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true
        username: user
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true

security:
  jwt:
    token:
      secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
      expire-length: 3600000
  aes256:
    key: aaaaaaaaaaaaaaaa
  invite-expire-length: 86400000

kakao:
  admin-key: ${KAKAO_ADMIN_KEY}
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}

logging:
  config: classpath:log4j2.yml
